apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sns.fullname" . }}
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.configMap.django.DJANGO_SETTINGS_MODULE }}
  DB_HOST: {{ include "sns.db.fullname" . }}
