apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sns
  namespace: default
spec:
  encryptedData:
    DJANGO_SECRET_KEY: AgBQ3dToXGfJ2RLXZJmNBhLXA1mLQZLroMalsG5+3icwF5q3BE/50/+xzTaTvcvMu6caC7nkD6Jyjt8oFbIMvE7TAeMyIeY6YVq0oAAD4BdK5ywsrnTgyW7pilLQ8kl+K1VxwWnxcJWyYEQw1t1YYw6tk23iTLZtV8Cf7LDdcsPsvRCO6/9uJ7dytM02meonolSjv9SJjJhQLVIMwk/GbvQeLam5xRTDuP9ConAEQ0lvx2nseppd8kb1JTdlS4VGj4VhVZb4d7pHA1PPnby6lx2Zr7qfH3+wwXBffdXOUszk+PpZ57EPmbIhvJHBIqRfKz/ZkOjcJvzAtUjgmevFhuXkCX+Lx6TzhFbCNFzcVlQl3+5gskvxnkOB2ib73lBDIxFTEv9Or3Zw/LQJBVgZL8Cn2nEOBactWVNQGH6R2tZLxK9RHgnwhYT1vvb8Pzda5RVHLM6Kn+Xgh/YnwOPRQkmD1+qOEIVEJPpwkH7xpvZd9sDb6jfdzUDKPR1bOLAcboQJ+D6WAqDPGF9Cqp2dI2bCOM6apRWy8xMwJgtGCWiNrMrnqeWFLXgKue3w8prhs7I8Y310lCfVYa6Ez0jGJihV/abYMf3rt8h6xRwEc+mw9ZOQ9P6dNoTqGRyNFeZ3KebkEHM3th0zB+bsQ/Oo9nq7/nsCuIC01BA54sYAxX2Q95MG5LvOzhdzdWp59N7cl1tNDsQ4gfjNDih5RsRLobu4m51wefB00J2jfeUS1S6VBoXEMrEtAEnKYH4=
  template:
    metadata:
      creationTimestamp: null
      name: sns
      namespace: default
    type: Opaque
---
