# Generated by Django 4.2.5 on 2023-09-13 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PostListAPI", "0002_alter_follow_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
    ]
