# Generated by Django 4.2.5 on 2023-09-13 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("PostListAPI", "0003_rename_author_post_user_remove_post_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="update_date",
            new_name="updated_date",
        ),
    ]
