# Generated by Django 4.2.5 on 2023-09-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("PostListAPI", "0005_post_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
