name: CI process

on:
  # pull_request:
  workflow_dispatch:
  push:
    branches:
      - "main"

env:
  IMAGE: ${{ vars.NCP_CONTAINER_REGISTRY }}/sns-app
  IMAGE_TAG: ${{ vars.NCP_CONTAINER_REGISTRY }}/sns-app:latest

jobs:
  lint:
    name: Check lint (black)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install black
        run: pip install black

      - name: Check black
        run: black --check app

  build_push_to_ncp:
    needs: lint
    name: Build Image
    runs-on: ubuntu-latest
    outputs:
      NEW_TAG: ${{ steps.check_tag.outputs.NEW_TAG }}
    steps:
      # checkout to the branch and get the codes
      - name: Checkout code
        uses: actions/checkout@v3

      - name: test
        run: |
          docker-compose -f docker-compose.test.yaml up --build -d
          docker-compose -f docker-compose.test.yaml run sns-app python manage.py test

      - name: post-test
        run: |
          docker-compose -f docker-compose.test.yaml down

      # buildx - support amd64, arm64
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      # NCP Login
      - name: Login to NCR
        uses: docker/login-action@v2
        with:
          # registry: where to login
          registry: ${{ vars.NCP_CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.IVAN_SNS }}
          default_bump: false
          # fix: - patch, feat: - minor, BREAKING CHANGE: - major

      - name: Check if new_tag exists
        id: check_tag
        run: |
          echo "NEW_TAG=${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_OUTPUT

      - name: Create a GitHub release
        if: ${{ env.NEW_TAG != '' }}
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.IVAN_SNS }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: create TAG
        id: created_tag
        run: |
          if [[ "${{ env.NEW_TAG }}" != "" ]]; then
              echo "Using version tag: ${{ env.NEW_TAG }}"
              echo "TAG=${{ env.NEW_TAG }}" >> $GITHUB_ENV
          else
              TIMESTAMP=$(date '+%s')
              echo "Using timestamp tag: $TIMESTAMP"
              echo "TAG=$TIMESTAMP" >> $GITHUB_ENV
          fi

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: app
          push: true
          tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ env.TAG }}"
          platforms: linux/amd64,linux/arm64
